/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library.mangement.system;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import library.mangement.system.database.connector;

/**
 *
 * @author HUAWEI
 */
public class History extends javax.swing.JFrame {

    /**
     * Creates new form History
     */
    public History() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 95, 1000, 180));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 73, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Issue Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 49, 150, 28));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 342, 1000, 180));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Returned Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, 28));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        //isseud details
        try{
            Connection con=connector.getconnect();
            Statement st=con.createStatement();
            ResultSet rs1=st.executeQuery("Select COUNT(*) as count from issued_book WHERE Return_Status='NO'");
            rs1.next();
            int n=rs1.getInt("count");
            String columns[] = { "Student ID","Student Name","Department", "Book ID", "Book Name","Author","Isuue Date","Due Date"};
            String data[][] = new String[n][8];
            //System.out.println(n);
            int i=0;
            ResultSet rs= st.executeQuery("SELECT student.ID,student.Name,student.Dept,book.id,book.bookname, book.author,issued_book.issueddate,issued_book.duedate from(( student INNER JOIN issued_book ON student.ID=issued_book.studentid  AND issued_book.Return_Status='NO') INNER JOIN book ON book.id=issued_book.bookid)");
            while(rs.next()){
                //System.out.println("check");
                data[i][0]=rs.getString("ID");
                data[i][1]=rs.getString("Name");
                data[i][2]=rs.getString("Dept");
                data[i][3]=rs.getString("book.id");
                //System.out.println("check");
                data[i][4]=rs.getString("bookname");
                //System.out.println("check");
                data[i][5]=rs.getString("author");
                data[i][6]=rs.getString("issueddate");
                data[i][7]=rs.getString("duedate");
                i++;
            }
             DefaultTableModel model = new DefaultTableModel(data, columns);
             jTable1.setModel(model);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Connection Error");
            setVisible(false);
            
        }
        
        // Return details 
         try{
            Connection con=connector.getconnect();
            Statement st=con.createStatement();
            ResultSet rs1=st.executeQuery("Select COUNT(*) as count from issued_book WHERE Return_Status='YES'");
            rs1.next();
            int n=rs1.getInt("count");
            String columns[] = { "Student ID","Student Name","Department", "Book ID", "Book Name","Author","Isuue Date","Due Date"};
            String data[][] = new String[n][8];
           // System.out.println(n);
            int i=0;
            ResultSet rs= st.executeQuery("SELECT student.ID,student.Name,student.Dept, book.id,book.bookname, book.author,issued_book.issueddate,issued_book.duedate from(( student INNER JOIN issued_book ON student.ID=issued_book.studentid  AND issued_book.Return_Status='YES') INNER JOIN book ON book.id=issued_book.bookid)");
            while(rs.next()){
                //System.out.println("check");
                data[i][0]=rs.getString("ID");
                data[i][1]=rs.getString("Name");
                data[i][2]=rs.getString("Dept");
                data[i][3]=rs.getString("book.id");
                //System.out.println("check");
                data[i][4]=rs.getString("bookname");
                //System.out.println("check");
                data[i][5]=rs.getString("author");
                data[i][6]=rs.getString("issueddate");
                data[i][7]=rs.getString("duedate");
                i++;
            }
             DefaultTableModel model = new DefaultTableModel(data, columns);
             jTable2.setModel(model);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Connection Error");
            setVisible(false);
            
        }
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
